=== irisnet/coin-registry/relayers/relayer.schema.json
{
    "$schema":"https://json-schema.org/draft/2020-12/schema",
    "$id":"https://github.com/irisnet/iob-registry/tree/main/relayers/relayer.schema.json",
    "title":"relayer registry",
    "description":"relayer registry",
    "type":"object",
    "properties":{
        "team_name":{
            "type":"string"
        },
        "team_logo":{
            "type":"string"
        },
        "contact":{
            "website":{
                "type":"string"
            },
            "github":{
                "type":"string"
            },
            "telegram":{
                "type":"string"
            },
            "twitter":{
                "type":"string"
            },
            "medium":{
                "type":"string"
            },
            "discord":{
                "type":"string"
            }
        },
        "introduction":{
            "type":"array",
            "items":{
                "type":"string"
            }
        },
        "addresses":{
            "type":"array",
            "items":{
                "type":"object",
                "patternProperties":{
                    "^[a-z]+$":{
                        "type":"string",
                        "description":"relayer address of chain-id"
                    }
                },
                "minProperties":2,
                "maxProperties":2
            },
            "minItems":1,
            "uniqueItems":true
        }
    },
    "required":[
        "team_name",
        "contact",
        "introduction",
        "addresses"
    ]
}

=== irisnet/coin-registry/relayers/GalaxyStaking/relayer_info.json
{
    "team_name":"GalaxyStaking.space üåë",
    "contact":{
        "website":"https://galaxystaking.space",
        "discord":"https://discord.gg/C4dhbW23WW",
        "telegram":"https://t.me/+CjNyaEDCtEY2YjRh"
    },
    "introduction":[
        "GalaxyStaking.space is a high quality ‚ö°Ô∏è validation service with a fixed commission rate of 5%. Eligible for airdrops üî• Auto-compound (rewards restake) is supported for Ledger and Keplr wallets. üîÑ Follow us on discord and telegram üöÄ"
    ],
    "addresses":[
        {
            "evmos_9001-2":"evmos14jjwzpde80hx9m97pmm5z4c0eydyrn83ndlxrh",
            "crypto-org-chain-mainnet-1":"cro1lwymrvh7vpwzqfkgpvjtz2y5gqelw4m7tq0w3e"
        },
        {
            "osmosis-1":"osmo1t76d0xn5r54v4s7n0w4t2kgpx9fce3axmz2cye",
            "crypto-org-chain-mainnet-1":"cro1lwymrvh7vpwzqfkgpvjtz2y5gqelw4m7tq0w3e"
        },
        {
            "evmos_9001-2":"evmos14jjwzpde80hx9m97pmm5z4c0eydyrn83ndlxrh",
            "osmosis-1":"osmo1t76d0xn5r54v4s7n0w4t2kgpx9fce3axmz2cye"
        }
    ]
}

=== irisnet/coin-registry/relayers/GATA HUB/relayer_info.json
{
    "team_name":"GATA HUB",
    "team_logo":"https://s3.amazonaws.com/keybase_processed_uploads/fd84e961633cef5f59f07fc847d56b05_360_360.jpg",
    "contact":{
        "website":"https://gatahub.zone",
        "github":"https://github.com/GATA-HUB",
        "twitter":"https://twitter.com/GataDaoZone",
        "discord":"https://discord.com/invite/4MCrtaCetp"
    },
    "introduction":[
        "Cat brings you the max rewards. Decentralized community-owned public infrastucture, trusted by thousands of delegators with millions of funds. Join GATA family üêæ"
    ],
    "addresses":[
       {
         "osmosis-1":"osmo129k9pj8yk58278q8l6j00azdxfjvz93kp37pak",
         "cosmoshub-4":"cosmos1zy7xyypdwje7w56rdz67pjxtjyk2t4ms5ak23c"
       },
       {
         "osmosis-1":"osmo129k9pj8yk58278q8l6j00azdxfjvz93kp37pak",
         "akashnet-2":"akash182ydqc6grkqyuxqmte4dh40jw4sw32jx2x7dyz"
       },
       {
         "osmosis-1":"osmo129k9pj8yk58278q8l6j00azdxfjvz93kp37pak",
         "teritori-1":"tori1hghqe5k6jj5ll0fl3wg3prandw07q2h2r30xnk"
       },
       {
         "osmosis-1":"osmo129k9pj8yk58278q8l6j00azdxfjvz93kp37pak",
         "stargaze-1":"stars14g6emx2jsv2sl2e5685hmpnvrzcfnzwqfffa0n"
       },
       {
         "osmosis-1":"osmo129k9pj8yk58278q8l6j00azdxfjvz93kp37pak",
         "juno-1":"juno1kqmzy5gph45f57hqdlchqsktk82ntmsxlen2j6"
       },
       {
         "osmosis-1":"osmo129k9pj8yk58278q8l6j00azdxfjvz93kp37pak",
         "omniflixhub-1":"omniflix1tfa6axplvpt0ucsur4zv56a5gq8x6x0nr5z3qa"
       },
       {
         "osmosis-1":"osmo129k9pj8yk58278q8l6j00azdxfjvz93kp37pak",
         "neutron-1":"neutron1uyv59p94h6g9ta2xucrphpu2l5ydce0h5lt7z0"
       },
       {
         "osmosis-1":"osmo129k9pj8yk58278q8l6j00azdxfjvz93kp37pak",
         "stride-1":"stride1texfv73p49gv69rl8wehtn9tnvkt9676564tyh"
       },
       {
         "cosmoshub-4":"cosmos1zy7xyypdwje7w56rdz67pjxtjyk2t4ms5ak23c",
         "neutron-1":"neutron1uyv59p94h6g9ta2xucrphpu2l5ydce0h5lt7z0"
       },
       {
         "cosmoshub-4":"cosmos1zy7xyypdwje7w56rdz67pjxtjyk2t4ms5ak23c",
         "stride-1":"stride1texfv73p49gv69rl8wehtn9tnvkt9676564tyh"
       },
       {
         "cosmoshub-4":"cosmos1zy7xyypdwje7w56rdz67pjxtjyk2t4ms5ak23c",
         "juno-1":"juno1kqmzy5gph45f57hqdlchqsktk82ntmsxlen2j6"
       },
       {
         "cosmoshub-4":"cosmos1zy7xyypdwje7w56rdz67pjxtjyk2t4ms5ak23c",
         "teritori-1":"tori1hghqe5k6jj5ll0fl3wg3prandw07q2h2r30xnk"
       },
       {
         "cosmoshub-4":"cosmos1zy7xyypdwje7w56rdz67pjxtjyk2t4ms5ak23c",
         "omniflixhub-1":"omniflix1tfa6axplvpt0ucsur4zv56a5gq8x6x0nr5z3qa"
       },
       {
         "cosmoshub-4":"cosmos1zy7xyypdwje7w56rdz67pjxtjyk2t4ms5ak23c",
         "akashnet-2":"akash182ydqc6grkqyuxqmte4dh40jw4sw32jx2x7dyz"
       },
       {
         "stride-1":"stride1texfv73p49gv69rl8wehtn9tnvkt9676564tyh",
         "neutron-1":"neutron1uyv59p94h6g9ta2xucrphpu2l5ydce0h5lt7z0"
       }
    ]
}

=== irisnet/coin-registry/relayers/example_relayer.json
{
    "team_name": "IRIS Foundation",
    "team_logo": "",
    "contact": {
      "website" : "https://irisnet.org/",
      "github": "https://github.com/irisnet",
      "telegram": "https://t.me/irisnetwork",
      "twitter": "https://twitter.com/irisnetwork",
      "medium": "https://medium.com/irisnet-blog",
      "discord": "https://discord.com/invite/bmhu9F9xbX"
    },
    "introduction": [
      "IRISnet (a.k.a IRIS Hub) is designed to be the foundation for the next generation distributed applications. Built with Cosmos-SDK, IRIS Hub enables cross-chain interoperability through a unified service model, while providing a variety of modules to support DeFi applications.",
      "IRISnet dev teams include Bianjie (https://www.bianjie.ai/), a national award-winning blockchain technology team based in Shanghai, and Tendermint (https://tendermint.com/), the world-famous team that created the Tendermint consensus engine and the Cosmos project."
    ],
    "addresses": [
        {
            "irishub-1": "iaa1cf8ufk9mqtj48zj9l4pupyfeqjwh7fjms67e50",
            "osmosis-1": "osmo1cf8ufk9mqtj48zj9l4pupyfeqjwh7fjmdrdcqv"
        },
        {
            "irishub-1": "iaa1cf8ufk9mqtj48zj9l4pupyfeqjwh7fjms67e50",
            "cosmoshub-4": "cosmos1cf8ufk9mqtj48zj9l4pupyfeqjwh7fjm9c7gk7"
        },
        {
            "irishub-1": "iaa1cf8ufk9mqtj48zj9l4pupyfeqjwh7fjms67e50",
            "gravity-bridge-3": "gravity1cf8ufk9mqtj48zj9l4pupyfeqjwh7fjmpgvsnk"
        }
    ]
  }

=== irisnet/coin-registry/relayers/WhisperNode/relayer_info.json
{
    "team_name": "WhisperNode ü§ê",
    "team_logo": "https://github.com/irisnet/iob-registry/raw/main/relayers/WhisperNode/images/WhisperNode.png",
    "contact": {
        "website": "https://whispernode.com",
        "github": "https://github.com/whispernode",
        "twitter": "https://twitter.com/whispernode",
        "discord": "https://discord.gg/4E5KZsRtjE",
        "telegram": "https://t.me/team_whispernode"
    },
    "introduction": [
        "WhisperNode is a community validator & infrastructure provider. Consider supporting our IBC relaying efforts by delegating to our validator nodes."
    ],
    "addresses": [
        {
            "akashnet-2": "akash1ryq6zncdxpdnnwhn9h24ar48ap9zkqgl5xpdnk",
            "cosmoshub-4": "cosmos1ryq6zncdxpdnnwhn9h24ar48ap9zkqgleav22v"
        },
        {
            "akashnet-2": "akash1ryq6zncdxpdnnwhn9h24ar48ap9zkqgl5xpdnk",
            "osmosis-1": "osmo1ryq6zncdxpdnnwhn9h24ar48ap9zkqgl3xl6u7"
        },
        {
            "axelar-dojo-1": "axelar1ryq6zncdxpdnnwhn9h24ar48ap9zkqglan6zpd",
            "cosmoshub-4": "cosmos1ryq6zncdxpdnnwhn9h24ar48ap9zkqgleav22v"
        },
        {
            "axelar-dojo-1": "axelar1ryq6zncdxpdnnwhn9h24ar48ap9zkqglan6zpd",
            "injective-1": "inj1jszj9xyh2eh8lx25u88rsv7hmsytvwsvr6cne0"
        },
        {
            "axelar-dojo-1": "axelar1ryq6zncdxpdnnwhn9h24ar48ap9zkqglan6zpd",
            "canine-1": "jkl1ryq6zncdxpdnnwhn9h24ar48ap9zkqglqrzmnn"
        },
        {
            "axelar-dojo-1": "axelar1ryq6zncdxpdnnwhn9h24ar48ap9zkqglan6zpd",
            "neutron-1": "neutron1ryq6zncdxpdnnwhn9h24ar48ap9zkqglaz9gst"
        },
        {
            "axelar-dojo-1": "axelar1ryq6zncdxpdnnwhn9h24ar48ap9zkqglan6zpd",
            "osmosis-1": "osmo1ryq6zncdxpdnnwhn9h24ar48ap9zkqgl3xl6u7"
        },
        {
            "axelar-dojo-1": "axelar19kzuzfmmy9wjr3cl0ss8wjzjup9g49hqzxn3p9",
            "secret-4": "secret1xpgjd2akpc8gmwez25keftpmlgs4aa3un463s7"
        },
        {
            "axelar-dojo-1": "axelar1ryq6zncdxpdnnwhn9h24ar48ap9zkqglan6zpd",
            "stride-1": "stride1ryq6zncdxpdnnwhn9h24ar48ap9zkqgl6kvk7q"
        },
        {
            "cheqd-mainnet-1": "cheqd1ryq6zncdxpdnnwhn9h24ar48ap9zkqglhlq2pa",
            "osmosis-1": "osmo1ryq6zncdxpdnnwhn9h24ar48ap9zkqgl3xl6u7"
        },
        {
            "cosmoshub-4": "cosmos1ryq6zncdxpdnnwhn9h24ar48ap9zkqgleav22v",
            "injective-1": "inj1jszj9xyh2eh8lx25u88rsv7hmsytvwsvr6cne0"
        },
        {
            "cosmoshub-4": "cosmos1ryq6zncdxpdnnwhn9h24ar48ap9zkqgleav22v",
            "neutron-1": "neutron1ryq6zncdxpdnnwhn9h24ar48ap9zkqglaz9gst"
        },
        {
            "cosmoshub-4": "cosmos1ryq6zncdxpdnnwhn9h24ar48ap9zkqgleav22v",
            "osmosis-1": "osmo1ryq6zncdxpdnnwhn9h24ar48ap9zkqgl3xl6u7"
        },
        {
            "cosmoshub-4": "cosmos1ryq6zncdxpdnnwhn9h24ar48ap9zkqgleav22v",
            "secret-4": "secret1xpgjd2akpc8gmwez25keftpmlgs4aa3un463s7"
        },
        {
            "cosmoshub-4": "cosmos1ryq6zncdxpdnnwhn9h24ar48ap9zkqgleav22v",
            "stride-1": "stride1ryq6zncdxpdnnwhn9h24ar48ap9zkqgl6kvk7q"
        },
        {
            "injective-1": "inj1jszj9xyh2eh8lx25u88rsv7hmsytvwsvr6cne0",
            "neutron-1": "neutron1ryq6zncdxpdnnwhn9h24ar48ap9zkqglaz9gst"
        },
        {
            "injective-1": "inj1jszj9xyh2eh8lx25u88rsv7hmsytvwsvr6cne0",
            "osmosis-1": "osmo1ryq6zncdxpdnnwhn9h24ar48ap9zkqgl3xl6u7"
        },
        {
            "injective-1": "inj1jszj9xyh2eh8lx25u88rsv7hmsytvwsvr6cne0",
            "secret-4": "secret1xpgjd2akpc8gmwez25keftpmlgs4aa3un463s7"
        },
        {
            "injective-1": "inj1jszj9xyh2eh8lx25u88rsv7hmsytvwsvr6cne0",
            "stride-1": "stride1ryq6zncdxpdnnwhn9h24ar48ap9zkqgl6kvk7q"
        },
        {
            "canine-1": "jkl1ryq6zncdxpdnnwhn9h24ar48ap9zkqglqrzmnn",
            "osmosis-1": "osmo1ryq6zncdxpdnnwhn9h24ar48ap9zkqgl3xl6u7"
        },
        {
            "canine-1": "jkl1ryq6zncdxpdnnwhn9h24ar48ap9zkqglqrzmnn",
            "secret-4": "secret1xpgjd2akpc8gmwez25keftpmlgs4aa3un463s7"
        },
        {
            "neutron-1": "neutron1ryq6zncdxpdnnwhn9h24ar48ap9zkqglaz9gst",
            "osmosis-1": "osmo1ryq6zncdxpdnnwhn9h24ar48ap9zkqgl3xl6u7"
        },
        {
            "neutron-1": "neutron1ryq6zncdxpdnnwhn9h24ar48ap9zkqglaz9gst",
            "secret-4": "secret1xpgjd2akpc8gmwez25keftpmlgs4aa3un463s7"
        },
        {
            "neutron-1": "neutron1ryq6zncdxpdnnwhn9h24ar48ap9zkqglaz9gst",
            "stride-1": "stride1ryq6zncdxpdnnwhn9h24ar48ap9zkqgl6kvk7q"
        },
        {
            "osmosis-1": "osmo1ryq6zncdxpdnnwhn9h24ar48ap9zkqgl3xl6u7",
            "secret-4": "secret1xpgjd2akpc8gmwez25keftpmlgs4aa3un463s7"
        },
        {
            "osmosis-1": "osmo1ryq6zncdxpdnnwhn9h24ar48ap9zkqgl3xl6u7",
            "stride-1": "stride1ryq6zncdxpdnnwhn9h24ar48ap9zkqgl6kvk7q"
        },
        {
            "secret-4": "secret1xpgjd2akpc8gmwez25keftpmlgs4aa3un463s7",
            "stride-1": "stride1ryq6zncdxpdnnwhn9h24ar48ap9zkqgl6kvk7q"
        }
    ]
}

=== irisnet/coin-registry/relayers/kjnodes/relayer_info.json
{
    "team_name": "kjnodes",
    "contact": {
        "website": "https://kjnodes.com",
        "twitter": "https://x.com/kjnodes",
        "telegram": "https://t.me/kjnodes",
        "github": "https://github.com/kjnodes"
    },
    "introduction": [
        "Trusted Proof of Stake validator across Cosmos universe. Active ecosystem contributor, IBC relayer and chain service provider since 2021."
    ],
    "addresses": [
        {
            "agoric-3": "agoric1twmgaeug7ymjq8c53ttstpl7rny43q8zh4rnh3"
        },
        {
            "archway-1": "archway1twmgaeug7ymjq8c53ttstpl7rny43q8zsragds"
        },
        {
            "bitcanna-1": "bcna1twmgaeug7ymjq8c53ttstpl7rny43q8zlc3d04"
        },
        {
            "cosmoshub-4": "cosmos1twmgaeug7ymjq8c53ttstpl7rny43q8z9gpv88"
        },
        {
            "jackal-1": "jkl1twmgaeug7ymjq8c53ttstpl7rny43q8zuk0a7c"
        },
        {
            "kaiyo-1": "kujira1twmgaeug7ymjq8c53ttstpl7rny43q8z5qr52d"
        },
        {
            "osmosis-1": "osmo1twmgaeug7ymjq8c53ttstpl7rny43q8zdnju34"
        },
        {
            "pirin-1": "nolus1twmgaeug7ymjq8c53ttstpl7rny43q8znc3n9z"
        },
        {
            "stride-1": "stride1twmgaeug7ymjq8c53ttstpl7rny43q8zxrpsnt"
        },
        {
            "quasar-1": "quasar1twmgaeug7ymjq8c53ttstpl7rny43q8zttm32z"
        },
        {
            "quicksilver-2": "quick1twmgaeug7ymjq8c53ttstpl7rny43q8zwv3774"
        },
        {
            "celestia": "celestia1twmgaeug7ymjq8c53ttstpl7rny43q8z5zsua2"
        },
        {
            "cataclysm-1": "nibi1twmgaeug7ymjq8c53ttstpl7rny43q8zjd94w5"
        }
    ]
}
